language: java
notifications:
  email: false
if: tag IS blank

before_install: chmod +x gradlew
install: "./gradlew setupCIWorkspace"
script: "./gradlew clean build"
jdk:
- oraclejdk8
before_cache:
- find $HOME/.gradle/ -name '*.lock' -print -exec rm -f {} \;
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
sudo: false

before_deploy:
  - export RELEASE_FILE_LIST=$(ls ./build/libs/* | tr '\n' ', ')
  - echo "deploying $RELEASE_FILE_LIST to GitHub releases"
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: N2DPWS7HeRRX9qI8QMAbtMWI2WQsZwTLCpF3slNSx1XvSKutnafvErN4KK78Ho0GGMjW47qg0JvzGeKD+VAQE84VrpIJ0tweIgSKacmKun7boFMqDn1vzGABNoVNBaVdWQ9GI6eVxuO/WWu60wvip0IHh6vPkGiW1trYLkWDehgrBT0ZmaB9XNc/8vNFzbGSRkWGmdITrQCvx2XLmfXmvtY0pW2l1nBmxHqll2N20fdO06WgD+qk1WaMRKmZzC8VOjZsCN152xxkQBmG03QSicLEzi4grzcLrswDblfkaTRwdzrsz3hPdQ1AaXzI5vtkLCWURtGvv+janlllm3iLrlDeQooDLyKcp9XtEU14pQtxQZvSKxvFWQct6thov+JC9UFuTeq1/fpb4XfqgqR8C1k0XSZVabgr0av7RwFItNPicNjlhGA3ps1RSJ8+NsGj4dZTLJr1icSTiZpKPHskNIOGe86dJpqaDWGKPC4hd/Uf1iVG/6S5Sj5mkuyzMW6e7iwXMW9T/HqEamEdONPiFhntNRxnbWvBA3lEZ6/8wrW1VWgBslKdFXaRjtOYG0/OFWjd7aZ4hzrmfVRzK6TL1wbQnqQM1ndMUtTfmj1EVqsoUIlbYRGRkZlizcjRieUaudMLUQXcZRSePbvddvD7aXpivSQnmPPwkB3g/0ClTRs=
  file_glob: true
  file: "{$RELEASE_FILE_LIST}"
  on:
    repo: DimensionalDevelopment/Dimensional-Industry
    branch: master
    tags: false
